export type OtherProject = {
  name: string;
  focus: {
    pl: string;
    en: string;
    ru: string;
  };
};

export const otherProjects: OtherProject[] = [
  { name: 'TikBudget', focus: { pl: 'budżecie domowym', en: 'home budgeting', ru: 'домашнем бюджете' } },
  { name: 'TikSavings', focus: { pl: 'oszczędzaniu pieniędzy', en: 'saving money', ru: 'сбережениях' } },
  { name: 'TikFamilyBudget', focus: { pl: 'budżecie rodzinnym', en: 'family budgeting', ru: 'семейном бюджете' } },
  { name: 'TikSideHustle', focus: { pl: 'pomysłach na dodatkowy zarobek', en: 'side income ideas', ru: 'идеях дополнительного заработка' } },
  { name: 'TikPriceScout', focus: { pl: 'porównywaniu cen', en: 'price comparison', ru: 'сравнении цен' } },
  { name: 'TikDealFinder', focus: { pl: 'wyszukiwaniu okazji', en: 'finding deals', ru: 'поиске выгодных предложений' } },
  { name: 'TikInvoiceMate', focus: { pl: 'fakturach i płatnościach', en: 'invoices and payments', ru: 'счетах и платежах' } },
  { name: 'TikTaxGuide', focus: { pl: 'porządkowaniu podatków', en: 'tax organization', ru: 'налогах' } },
  { name: 'TikFreelanceDesk', focus: { pl: 'organizacji zleceń', en: 'freelance workflows', ru: 'фриланс‑задачах' } },
  { name: 'TikResumePro', focus: { pl: 'CV i profilu zawodowym', en: 'resumes', ru: 'резюме' } },
  { name: 'TikInterviewPrep', focus: { pl: 'przygotowaniu do rozmów', en: 'interview prep', ru: 'собеседованиях' } },
  { name: 'TikCareerPath', focus: { pl: 'planowaniu kariery', en: 'career planning', ru: 'карьере' } },
  { name: 'TikSkillBoost', focus: { pl: 'rozwoju umiejętności', en: 'skill building', ru: 'навыках' } },
  { name: 'TikCourseMaker', focus: { pl: 'tworzeniu kursów', en: 'course creation', ru: 'создании курсов' } },
  { name: 'TikLessonPlan', focus: { pl: 'planach lekcji', en: 'lesson planning', ru: 'планах уроков' } },
  { name: 'TikQuizMaker', focus: { pl: 'tworzeniu quizów', en: 'quiz creation', ru: 'создании тестов' } },
  { name: 'TikStudyBuddy', focus: { pl: 'planowaniu nauki', en: 'study planning', ru: 'учёбе' } },
  { name: 'TikNoteSync', focus: { pl: 'notatkach i porządkowaniu', en: 'note organization', ru: 'заметках' } },
  { name: 'TikMemoryCoach', focus: { pl: 'ćwiczeniu pamięci', en: 'memory training', ru: 'памяти' } },
  { name: 'TikReadingCoach', focus: { pl: 'czytaniu i zrozumieniu', en: 'reading comprehension', ru: 'чтении' } },
  { name: 'TikLanguageCoach', focus: { pl: 'nauce języków', en: 'language learning', ru: 'языках' } },
  { name: 'TikPronunciation', focus: { pl: 'wymowie', en: 'pronunciation', ru: 'произношении' } },
  { name: 'TikWritingAid', focus: { pl: 'pisaniu i korekcie', en: 'writing and proofreading', ru: 'письме' } },
  { name: 'TikExplainIt', focus: { pl: 'tłumaczeniu trudnych pojęć', en: 'explaining complex ideas', ru: 'объяснении' } },
  { name: 'TikVisualAid', focus: { pl: 'wizualizacjach i diagramach', en: 'visuals and diagrams', ru: 'визуализациях' } },
  { name: 'TikSlideMaker', focus: { pl: 'tworzeniu prezentacji', en: 'presentations', ru: 'презентациях' } },
  { name: 'TikMeetingNotes', focus: { pl: 'notatkach ze spotkań', en: 'meeting notes', ru: 'заметках встреч' } },
  { name: 'TikCalendarPlus', focus: { pl: 'planowaniu dnia', en: 'daily scheduling', ru: 'планировании дня' } },
  { name: 'TikFocusMode', focus: { pl: 'koncentracji', en: 'focus', ru: 'концентрации' } },
  { name: 'TikHabitForge', focus: { pl: 'budowaniu nawyków', en: 'habit building', ru: 'привычках' } },
  { name: 'TikJournal', focus: { pl: 'dzienniku i refleksji', en: 'journaling', ru: 'дневнике' } },
  { name: 'TikGratitude', focus: { pl: 'wdzięczności', en: 'gratitude', ru: 'благодарности' } },
  { name: 'TikMindful', focus: { pl: 'uważności', en: 'mindfulness', ru: 'осознанности' } },
  { name: 'TikCalmSpace', focus: { pl: 'redukcji stresu', en: 'stress reduction', ru: 'стрессе' } },
  { name: 'TikSleepBetter', focus: { pl: 'śnie i regeneracji', en: 'sleep', ru: 'сне' } },
  { name: 'TikHydrate', focus: { pl: 'nawodnieniu', en: 'hydration', ru: 'воде' } },
  { name: 'TikMealPlan', focus: { pl: 'planowaniu posiłków', en: 'meal planning', ru: 'питании' } },
  { name: 'TikHealthyShop', focus: { pl: 'zdrowych zakupach', en: 'healthy shopping', ru: 'покупках' } },
  { name: 'TikRecipeFlow', focus: { pl: 'przepisach', en: 'recipes', ru: 'рецептах' } },
  { name: 'TikFoodWasteLess', focus: { pl: 'ograniczaniu marnowania jedzenia', en: 'food waste reduction', ru: 'пищевых отходах' } },
  { name: 'TikFitnessPlan', focus: { pl: 'planie treningów', en: 'fitness planning', ru: 'тренировках' } },
  { name: 'TikYogaFlow', focus: { pl: 'jodze', en: 'yoga', ru: 'йоге' } },
  { name: 'TikRunCoach', focus: { pl: 'bieganiu', en: 'running', ru: 'беге' } },
  { name: 'TikWalkBuddy', focus: { pl: 'spacerach', en: 'walking', ru: 'прогулках' } },
  { name: 'TikPostureFix', focus: { pl: 'postawie', en: 'posture', ru: 'осанке' } },
  { name: 'TikStretch', focus: { pl: 'rozciąganiu', en: 'stretching', ru: 'растяжке' } },
  { name: 'TikHomeFix', focus: { pl: 'drobnych naprawach', en: 'home fixes', ru: 'ремонте дома' } },
  { name: 'TikDIYHelper', focus: { pl: 'projektach DIY', en: 'DIY projects', ru: 'DIY‑проектах' } },
  { name: 'TikCleanRoutine', focus: { pl: 'sprzątaniu', en: 'cleaning', ru: 'уборке' } },
  { name: 'TikLaundryCare', focus: { pl: 'praniu', en: 'laundry', ru: 'стирке' } },
  { name: 'TikGardenCare', focus: { pl: 'ogrodzie', en: 'gardening', ru: 'саде' } },
  { name: 'TikPlantDoctor', focus: { pl: 'pielęgnacji roślin', en: 'plant care', ru: 'растениях' } },
  { name: 'TikPetCare', focus: { pl: 'opiece nad zwierzętami', en: 'pet care', ru: 'питомцах' } },
  { name: 'TikPetHealth', focus: { pl: 'zdrowiu zwierząt', en: 'pet health', ru: 'здоровье животных' } },
  { name: 'TikFamilyPlan', focus: { pl: 'planie rodzinnym', en: 'family planning', ru: 'семейных делах' } },
  { name: 'TikKidsLearn', focus: { pl: 'nauce dzieci', en: 'kids learning', ru: 'обучении детей' } },
  { name: 'TikSafetyHome', focus: { pl: 'bezpieczeństwie domu', en: 'home safety', ru: 'безопасности дома' } },
  { name: 'TikFirstAidGuide', focus: { pl: 'pierwszej pomocy', en: 'first aid', ru: 'первой помощи' } },
  { name: 'TikEmergencyReady', focus: { pl: 'gotowości awaryjnej', en: 'emergency readiness', ru: 'готовности' } },
  { name: 'TikTravelSafe', focus: { pl: 'bezpiecznych podróżach', en: 'travel safety', ru: 'безопасности в поездках' } },
  { name: 'TikRoadTrip', focus: { pl: 'trasach i planie podróży', en: 'trip planning', ru: 'маршрутах' } },
  { name: 'TikDriverBuddy', focus: { pl: 'wskazówkach dla kierowców', en: 'driving tips', ru: 'вождении' } },
  { name: 'TikCarCare', focus: { pl: 'obsłudze auta', en: 'car care', ru: 'авто' } },
  { name: 'TikBikeCare', focus: { pl: 'serwisie roweru', en: 'bike care', ru: 'велосипеде' } },
  { name: 'TikCityGuide', focus: { pl: 'lokalnych miejscach', en: 'local guides', ru: 'городе' } },
  { name: 'TikLocalFind', focus: { pl: 'odkrywaniu lokalnych usług', en: 'local services', ru: 'сервисах' } },
  { name: 'TikVolunteer', focus: { pl: 'wolontariacie', en: 'volunteering', ru: 'волонтёрстве' } },
  { name: 'TikCommunity', focus: { pl: 'inicjatywach społecznych', en: 'community initiatives', ru: 'сообществах' } },
  { name: 'TikDonationHub', focus: { pl: 'darowiznach', en: 'donations', ru: 'пожертвованиях' } },
  { name: 'TikTimeBank', focus: { pl: 'wymianie czasu', en: 'time banking', ru: 'обмене временем' } },
  { name: 'TikSmallBiz', focus: { pl: 'małych firmach', en: 'small business', ru: 'малом бизнесе' } },
  { name: 'TikShopHelper', focus: { pl: 'obsłudze sklepu', en: 'shop operations', ru: 'магазине' } },
  { name: 'TikInventory', focus: { pl: 'stanach magazynowych', en: 'inventory', ru: 'складских запасах' } },
  { name: 'TikWarehouse', focus: { pl: 'organizacji magazynu', en: 'warehouse', ru: 'складе' } },
  { name: 'TikLogistics', focus: { pl: 'logistyce', en: 'logistics', ru: 'логистике' } },
  { name: 'TikSupplyChain', focus: { pl: 'łańcuchu dostaw', en: 'supply chain', ru: 'цепочке поставок' } },
  { name: 'TikCustomerCare', focus: { pl: 'obsłudze klienta', en: 'customer support', ru: 'поддержке клиентов' } },
  { name: 'TikSupportDesk', focus: { pl: 'zgłoszeniach i ticketach', en: 'support tickets', ru: 'тикетах' } },
  { name: 'TikEmailTidy', focus: { pl: 'porządkowaniu poczty', en: 'email organization', ru: 'почте' } },
  { name: 'TikDocScan', focus: { pl: 'skanowaniu dokumentów', en: 'document scanning', ru: 'документах' } },
  { name: 'TikContractCheck', focus: { pl: 'weryfikacji umów', en: 'contract checks', ru: 'договорах' } },
  { name: 'TikPrivacyCheck', focus: { pl: 'prywatności', en: 'privacy checks', ru: 'приватности' } },
  { name: 'TikPasswordSafe', focus: { pl: 'bezpieczeństwie haseł', en: 'password safety', ru: 'паролях' } },
  { name: 'TikScamAlert', focus: { pl: 'wykrywaniu oszustw', en: 'scam detection', ru: 'мошенничестве' } },
  { name: 'TikFraudGuard', focus: { pl: 'ochronie przed fraudem', en: 'fraud protection', ru: 'мошенничестве' } },
  { name: 'TikEnergySaver', focus: { pl: 'oszczędzaniu energii', en: 'energy saving', ru: 'энергии' } },
  { name: 'TikGreenHome', focus: { pl: 'ekologii w domu', en: 'green home', ru: 'экологии дома' } },
  { name: 'TikRecycle', focus: { pl: 'recyklingu', en: 'recycling', ru: 'переработке' } },
  { name: 'TikWaterSaver', focus: { pl: 'oszczędzaniu wody', en: 'water saving', ru: 'воде' } },
  { name: 'TikAccessibility', focus: { pl: 'dostępności', en: 'accessibility', ru: 'доступности' } },
  { name: 'TikReadAloud', focus: { pl: 'czytaniu na głos', en: 'read aloud', ru: 'чтении вслух' } },
  { name: 'TikSignAssist', focus: { pl: 'komunikacji wspomagającej', en: 'assisted communication', ru: 'коммуникации' } },
  { name: 'TikSpeechCoach', focus: { pl: 'mowie i dykcji', en: 'speech coaching', ru: 'речи' } },
  { name: 'TikPublicSpeak', focus: { pl: 'wystąpieniach publicznych', en: 'public speaking', ru: 'публичных выступлениях' } },
  { name: 'TikNegotiation', focus: { pl: 'negocjacjach', en: 'negotiation', ru: 'переговорах' } },
  { name: 'TikContentPlanner', focus: { pl: 'planowaniu treści', en: 'content planning', ru: 'контенте' } },
  { name: 'TikCreatorTools', focus: { pl: 'narzędziach dla twórców', en: 'creator tools', ru: 'создателях' } },
  { name: 'TikMarketTrends', focus: { pl: 'trendach rynkowych', en: 'market trends', ru: 'рыночных трендах' } },
  { name: 'TikBrandBoost', focus: { pl: 'budowaniu marki', en: 'branding', ru: 'брендинге' } },
  { name: 'TikAffiliateHelper', focus: { pl: 'programach partnerskich', en: 'affiliate programs', ru: 'партнёрских программах' } }
];
